version: '3.3'

services:
    rignet:
        build:
            context: .
        volumes:
            - ./data:/app/data
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          capabilities: [ gpu ]
                          count: 1
